import Image from 'next/image';

const FinalThoughts = () => {
  return (
    <div className="flex flex-col md:flex-row items-center justify-between p-6">
          <div className="md:w-1/2 p-4">
        <Image
          src="/final-thoughts.jpg"
          alt="GPT Rewriter"
          width={500}
          height={400}
          className="rounded-lg ml-12"
        />
      </div>
      <div className="md:w-1/2 p-4">
        <h2 className="text-2xl font-bold mb-4">Final Thoughts</h2>
        <p className="mb-4">
          The GPT rewriter is a humanize AI text tool that gives you the perfect solution to the issues with text that is generated by Chat GPT. The biggest problem with this kind of content is that it is often very robotic sounding, and AI detection tools can easily find this and label it as AI.
        </p>
        <p className="mb-4">
          The biggest issue with this is that it is said that many search engines will start to exclude AI content from their search results. This means that this can seriously affect the SEO efforts of many companies out there.
        </p>
        <p className="mb-4">
          The Chat GPT rewriter basically takes that content and rewrites it in a way that feels more human. This allows for that content to no longer be detectable to AI. The great thing about this is that it also makes the content friendlier for search engines to index.
        </p>
      </div>
    
    </div>
  );
};

export default FinalThoughts;
